defaults: &defaults
  working_directory: ~/repo

  steps:
    - checkout

    - run:
        name: install dependencies
        command: |
          sudo pip install pipenv
          pipenv install --dev

    - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          pipenv run python tests.py

    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

version: 2
jobs:
  build-python-3.6:
    <<: *defaults
    docker:
      - image: circleci/python:3.6.1
  build-python-3.5:
    <<: *defaults
    docker:
      - image: circleci/python:3.5.3
  build-python-3.4:
    <<: *defaults
    docker:
      - image: circleci/python:3.4.6
  build-python-3.3:
    <<: *defaults
    docker:
      - image: circleci/python:3.3.6

workflows:
  version: 2
  build:
    jobs:
      - build-python-3.6
      - build-python-3.5
      - build-python-3.4
      - build-python-3.3